// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication_MVC.Data;

namespace WebApplication_MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApplication_MVC.Models.Alquiler", b =>
                {
                    b.Property<int>("id_alquiler")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("abono_inicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("devuelto")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_carro")
                        .HasColumnType("int");

                    b.Property<int>("id_cliente")
                        .HasColumnType("int");

                    b.Property<decimal>("saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("tiempo")
                        .HasColumnType("int");

                    b.Property<decimal>("valor_total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_alquiler");

                    b.ToTable("Alquiler");
                });

            modelBuilder.Entity("WebApplication_MVC.Models.Carro", b =>
                {
                    b.Property<int>("id_carro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("disponible")
                        .HasColumnType("bit");

                    b.Property<string>("marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("modelo")
                        .HasColumnType("int");

                    b.Property<string>("placa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_carro");

                    b.ToTable("Carro");
                });

            modelBuilder.Entity("WebApplication_MVC.Models.Cliente", b =>
                {
                    b.Property<int>("id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_cliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("WebApplication_MVC.Models.Contador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ventas_por_dia")
                        .HasColumnType("int");

                    b.Property<int>("ventas_por_mes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Contador");
                });

            modelBuilder.Entity("WebApplication_MVC.Models.Pagos", b =>
                {
                    b.Property<int>("id_pagos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_alquiler")
                        .HasColumnType("int");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_pagos");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("WebApplication_MVC.Models.Registro", b =>
                {
                    b.Property<int>("id_alquiler")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Fecha_Alquiler")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tiempo_Alquilado")
                        .HasColumnType("int");

                    b.Property<string>("cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("saldo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_alquiler");

                    b.ToTable("Registro");
                });
#pragma warning restore 612, 618
        }
    }
}
